[auth]
site_url = "https://flatmatchweb.vercel.app"
additional_redirect_urls = [
  "http://localhost:5173",
  "https://flatmatchweb.vercel.app"
]

[auth.external.google]
enabled = true
client_id = "env(VITE_GOOGLE_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_CLIENT_SECRET)"

[db]
port = 15432

[studio]
port = 15433

[api]
port = 15434
