import type { BookingRequest } from "src/entities/booking-request/booking-request";

export const mockBookingRequests: BookingRequest[] = [
	{
		createdAt: new Date("2025-08-01"),
		expectedDuration: { unit: "month", value: 6 },
		id: "booking_1",
		message: "Estoy interesada en alquilar desde septiembre",
		moveInDate: new Date("2025-09-01"),
		ownerId: "user_2",
		roomId: "room_1",
		status: "pending",
		tenantId: "user_1",
	},
	{
		createdAt: new Date("2025-08-02"),
		expectedDuration: { unit: "month", value: 12 },
		id: "booking_2",
		message: "Me gustaría reservar la habitación.",
		moveInDate: new Date("2025-09-01"),
		ownerId: "user_1",
		roomId: "room_1",
		status: "accepted",
		tenantId: "user_2",
	},
	{
		answer: "Lo siento, ya no está disponible.",
		createdAt: new Date("2025-08-03"),
		expectedDuration: { unit: "month", value: 3 },
		id: "booking_3",
		message: "La habitación ya no está disponible.",
		moveInDate: new Date("2025-09-15"),
		ownerId: "user_3",
		roomId: "room_2",
		status: "rejected",
		tenantId: "user_1",
	},
	{
		answer: "Entiendo, gracias por avisar.",
		createdAt: new Date("2025-08-04"),
		expectedDuration: { unit: "year", value: 1 },
		id: "booking_4",
		message: "He cambiado de planes, no puedo mudarme.",
		moveInDate: new Date("2025-10-01"),
		ownerId: "user_1",
		roomId: "room_3",
		status: "cancelled",
		tenantId: "user_2",
	},
];
