import type { BookingRequest } from "src/entities/booking-request/booking-request";

export const mockBookingRequests: BookingRequest[] = [
  {
    id: "booking_1",
    roomId: "room_1",
    tenantId: "user_1",
    ownerId: "user_2",
    createdAt: new Date("2025-08-01"),
    status: "pending",
    message: "Estoy interesada en alquilar desde septiembre",
    moveInDate: new Date("2025-09-01"),
    expectedDuration: { unit: "month", value: 6 },
  },
  {
    id: "booking_2",
    roomId: "room_1",
    tenantId: "user_2",
    ownerId: "user_1",
    createdAt: new Date("2025-08-02"),
    status: "accepted",
    message: "Me gustaría reservar la habitación.",
    moveInDate: new Date("2025-09-01"),
    expectedDuration: { unit: "month", value: 12 },
  },
  {
    id: "booking_3",
    roomId: "room_2",
    tenantId: "user_1",
    ownerId: "user_3",
    createdAt: new Date("2025-08-03"),
    status: "rejected",
    message: "La habitación ya no está disponible.",
    answer: "Lo siento, ya no está disponible.",
    moveInDate: new Date("2025-09-15"),
    expectedDuration: { unit: "month", value: 3 },
  },
  {
    id: "booking_4",
    roomId: "room_3",
    tenantId: "user_2",
    ownerId: "user_1",
    createdAt: new Date("2025-08-04"),
    status: "cancelled",
    message: "He cambiado de planes, no puedo mudarme.",
    answer: "Entiendo, gracias por avisar.",
    moveInDate: new Date("2025-10-01"),
    expectedDuration: { unit: "year", value: 1 },
  },
];
