import type { Room } from "src/entities/room/room";

export const mockRooms: Room[] = [
  {
    id: "room_1",
    status: "available",
    title: "Habitación luminosa en piso compartido en Gràcia",
    description: "Habitación con cama doble, escritorio y balcón en un piso con estudiantes internacionales.",
    createdAt: new Date("2024-07-10"),
    updatedAt: new Date(),
    rentType: "shared",
    location: {
      address: "Carrer de Verdi 45",
      city: "Barcelona",
      state: "Catalunya",
      country: "España",
      lat: 41.4000,
      lng: 2.1500,
      postalCode: "08012",
    },
    price: {
      amount: 480,
      currency: "EUR",
      paymentFrequency: "monthly",
      isIncluded: false,
      isNegotiable: true,
      additionalCosts: {
        utilities: 50,
        deposit: 500,
        otherFees: 20,
      },
    },
    commodities: {
      shared: {
        hasWifi: true,
        hasKitchen: true,
        hasHeating: true,
        hasAirConditioning: false,
        hasLaundry: true,
        hasElevator: false,
        isWheelchairAccessible: false,
      },
      whole: {
        area: 90,
        bedrooms: { individual: 2, shared: 1, double: 0 },
        bathrooms: 1,
        extras: {
          hasParking: false,
          hasPool: false,
          hasGarden: false,
          hasTerrace: true,
        },
        appliances: {
          hasTV: true,
          hasWashingMachine: true,
          hasDryer: false,
          hasDishwasher: false,
          hasMicrowave: true,
          hasRefrigerator: true,
          hasOven: true,
          hasCoffeeMaker: true,
        },
        areUtilitiesIncluded: false,
      },
      room: {
        area: 12,
        bedType: "double",
        hasWindow: true,
        hasBalcony: true,
        isFurnished: true,
        hasPrivateBathroom: false,
        hasWorkingDesk: true,
      },
    },
    rules: {
      petsAllowed: false,
      smokingAllowed: false,
      guestsAllowed: true,
      coupleAllowed: false,
      childrenAllowed: false,
      partiesAllowed: false,
      quietHours: { from: "22:00", to: "08:00" },
    },
    images: {
      main: 0,
      gallery: ["https://plus.unsplash.com/premium_photo-1676823553207-758c7a66e9bb?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=958&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
    },
    timings: {
      availableFrom: new Date("2025-09-01"),
      minimumStay: { unit: "month", value: 3 },
      maximumStay: { unit: "month", value: 12 },
    },
    whoIsLiving: {
      ownerLivesHere: false,
      currentTenants: { male: 1, female: 2, other: 0 },
    },
    contact: {
      owner: {
        name: "Jordi Puig",
        phone: "+34666666666",
        email: "jordi.puig@barcelona.com",
      },
    },
    isVerified: { date: new Date("2025-07-01") },
    preferences: {
      gender: { male: true, female: true, other: true },
      age: { min: 20, max: 35 },
      currentOccupation: { student: true, employed: true, unemployed: false, other: false },
    },
  }, {
    id: "room_2",
    status: "available",
    title: "Habitación individual con baño privado en Eixample",
    description: "Cómoda habitación con cama individual, escritorio y baño privado en piso moderno y tranquilo.",
    createdAt: new Date("2024-07-12"),
    updatedAt: new Date(),
    rentType: "shared",
    location: {
      address: "Carrer de Mallorca 120",
      city: "Barcelona",
      state: "Catalunya",
      country: "España",
      lat: 41.3902,
      lng: 2.1649,
      postalCode: "08036",
    },
    price: {
      amount: 600,
      currency: "EUR",
      paymentFrequency: "monthly",
      isIncluded: true,
      isNegotiable: false,
      additionalCosts: {
        utilities: 0,
        deposit: 600,
        otherFees: 0,
      },
    },
    commodities: {
      shared: {
        hasWifi: true,
        hasKitchen: true,
        hasHeating: true,
        hasAirConditioning: true,
        hasLaundry: true,
        hasElevator: true,
        isWheelchairAccessible: true,
      },
      whole: {
        area: 110,
        bedrooms: { individual: 3, shared: 0, double: 0 },
        bathrooms: 2,
        extras: {
          hasParking: true,
          hasPool: false,
          hasGarden: false,
          hasTerrace: false,
        },
        appliances: {
          hasTV: true,
          hasWashingMachine: true,
          hasDryer: true,
          hasDishwasher: true,
          hasMicrowave: true,
          hasRefrigerator: true,
          hasOven: true,
          hasCoffeeMaker: true,
        },
        areUtilitiesIncluded: true,
      },
      room: {
        area: 10,
        bedType: "single",
        hasWindow: true,
        hasBalcony: false,
        isFurnished: true,
        hasPrivateBathroom: true,
        hasWorkingDesk: true,
      },
    },
    rules: {
      petsAllowed: false,
      smokingAllowed: false,
      guestsAllowed: false,
      coupleAllowed: false,
      childrenAllowed: false,
      partiesAllowed: false,
      quietHours: { from: "22:00", to: "08:00" },
    },
    images: {
      main: 0,
      gallery: [
        "https://images.unsplash.com/photo-1615800002234-05c4d488696c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
        "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
      ],
    },
    timings: {
      availableFrom: new Date("2025-10-01"),
      minimumStay: { unit: "month", value: 6 },
      maximumStay: { unit: "month", value: 12 },
    },
    whoIsLiving: {
      ownerLivesHere: false,
      currentTenants: { male: 2, female: 0, other: 0 },
    },
    contact: {
      owner: {
        name: "Lucía Gómez",
        phone: "+34678901234",
        email: "lucia@eixampleliving.es",
      },
    },
    isVerified: { date: new Date("2025-07-15") },
    preferences: {
      gender: { male: true, female: true, other: false },
      age: { min: 22, max: 30 },
      currentOccupation: { student: true, employed: true, unemployed: false, other: false },
    },
  },
  {
    id: "room_3",
    status: "booked",
    title: "Habitación amplia con terraza en Sants",
    description: "Espaciosa habitación doble con salida a terraza privada, ideal para parejas o trabajadores.",
    createdAt: new Date("2024-07-15"),
    updatedAt: new Date(),
    rentType: "shared",
    location: {
      address: "Carrer de Sants 202",
      city: "Barcelona",
      state: "Catalunya",
      country: "España",
      lat: 41.3758,
      lng: 2.1343,
      postalCode: "08028",
    },
    price: {
      amount: 700,
      currency: "EUR",
      paymentFrequency: "monthly",
      isIncluded: false,
      isNegotiable: false,
      additionalCosts: {
        utilities: 60,
        deposit: 700,
        otherFees: 0,
      },
    },
    commodities: {
      shared: {
        hasWifi: true,
        hasKitchen: true,
        hasHeating: false,
        hasAirConditioning: true,
        hasLaundry: true,
        hasElevator: true,
        isWheelchairAccessible: false,
      },
      whole: {
        area: 85,
        bedrooms: { individual: 1, shared: 0, double: 2 },
        bathrooms: 1,
        extras: {
          hasParking: false,
          hasPool: false,
          hasGarden: false,
          hasTerrace: true,
        },
        appliances: {
          hasTV: true,
          hasWashingMachine: true,
          hasDryer: false,
          hasDishwasher: false,
          hasMicrowave: true,
          hasRefrigerator: true,
          hasOven: true,
          hasCoffeeMaker: false,
        },
        areUtilitiesIncluded: false,
      },
      room: {
        area: 18,
        bedType: "double",
        hasWindow: true,
        hasBalcony: false,
        isFurnished: true,
        hasPrivateBathroom: false,
        hasWorkingDesk: true,
      },
    },
    rules: {
      petsAllowed: true,
      smokingAllowed: true,
      guestsAllowed: true,
      coupleAllowed: true,
      childrenAllowed: false,
      partiesAllowed: false,
      quietHours: { from: "23:00", to: "07:00" },
    },
    images: {
      main: 1,
      gallery: [
        "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHJvb218ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHJvb218ZW58MHx8MHx8fDA%3D",
      ],
    },
    timings: {
      availableFrom: new Date("2025-09-15"),
      minimumStay: { unit: "month", value: 2 },
      maximumStay: { unit: "month", value: 6 },
    },
    whoIsLiving: {
      ownerLivesHere: true,
      currentTenants: { male: 0, female: 1, other: 0 },
    },
    contact: {
      owner: {
        name: "Marc Riera",
        phone: "+34932123456",
        email: "marc@pisosants.com",
      },
    },
    isVerified: { date: new Date("2025-07-05") },
    preferences: {
      gender: { male: true, female: true, other: true },
      age: { min: 25, max: 40 },
      currentOccupation: { student: false, employed: true, unemployed: false, other: false },
    },
  },
  {
    id: "room_4",
    status: "available",
    title: "Habitación económica en piso familiar en El Clot",
    description: "Ideal para estudiantes con presupuesto ajustado, en zona bien comunicada y tranquila.",
    createdAt: new Date("2024-06-30"),
    updatedAt: new Date(),
    rentType: "shared",
    location: {
      address: "Carrer de Rogent 78",
      city: "Barcelona",
      state: "Catalunya",
      country: "España",
      lat: 41.4110,
      lng: 2.1895,
      postalCode: "08026",
    },
    price: {
      amount: 350,
      currency: "EUR",
      paymentFrequency: "monthly",
      isIncluded: false,
      isNegotiable: true,
      additionalCosts: {
        utilities: 40,
        deposit: 300,
        otherFees: 0,
      },
    },
    commodities: {
      shared: {
        hasWifi: true,
        hasKitchen: true,
        hasHeating: true,
        hasAirConditioning: false,
        hasLaundry: true,
        hasElevator: false,
        isWheelchairAccessible: false,
      },
      whole: {
        area: 70,
        bedrooms: { individual: 2, shared: 0, double: 0 },
        bathrooms: 1,
        extras: {
          hasParking: false,
          hasPool: false,
          hasGarden: false,
          hasTerrace: false,
        },
        appliances: {
          hasTV: false,
          hasWashingMachine: true,
          hasDryer: false,
          hasDishwasher: false,
          hasMicrowave: true,
          hasRefrigerator: true,
          hasOven: true,
          hasCoffeeMaker: false,
        },
        areUtilitiesIncluded: false,
      },
      room: {
        area: 8,
        bedType: "single",
        hasWindow: true,
        hasBalcony: false,
        isFurnished: true,
        hasPrivateBathroom: false,
        hasWorkingDesk: true,
      },
    },
    rules: {
      petsAllowed: false,
      smokingAllowed: false,
      guestsAllowed: false,
      coupleAllowed: false,
      childrenAllowed: false,
      partiesAllowed: false,
      quietHours: { from: "22:30", to: "07:30" },
    },
    images: {
      main: 0,
      gallery: [
        "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cm9vbXxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1518012312832-96aea3c91144?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHJvb218ZW58MHx8MHx8fDA%3D",
      ],
    },
    timings: {
      availableFrom: new Date("2025-08-20"),
      minimumStay: { unit: "month", value: 1 },
      maximumStay: { unit: "month", value: 6 },
    },
    whoIsLiving: {
      ownerLivesHere: true,
      currentTenants: { male: 0, female: 1, other: 0 },
    },
    contact: {
      owner: {
        name: "Teresa López",
        phone: "+34666666667",
        email: "teresa@hogarfamiliar.com",
      },
    },
    isVerified: { date: new Date("2025-07-10") },
    preferences: {
      gender: { male: false, female: true, other: false },
      age: { min: 18, max: 28 },
      currentOccupation: { student: true, employed: false, unemployed: false, other: false },
    },
  },
];
