import type { Room } from "~/entities/room/room";

export const mockRooms: Room[] = [
	{
		commodities: {
			room: {
				area: 12,
				bedType: "double",
				hasBalcony: true,
				hasPrivateBathroom: false,
				hasWindow: true,
				hasWorkingDesk: true,
				isFurnished: true,
			},

			whole: {
				appliances: {
					hasAirConditioning: false,
					hasCoffeeMaker: true,
					hasDishwasher: false,
					hasDryer: false,
					hasElevator: false,
					hasHeating: true,
					hasLaundry: true,
					hasMicrowave: true,
					hasOven: true,
					hasRefrigerator: true,
					hasTV: true,
					hasWifi: true,
					isWheelchairAccessible: false,
				},
				area: 90,
				areUtilitiesIncluded: false,
				bathrooms: 1,
				bedrooms: { individual: 2, shared: 1 },
				extras: {
					hasGarden: false,
					hasParking: false,
					hasPool: false,
					hasTerrace: true,
				},
			},
		},
		contact: {
			owner: {
				email: "jordi.puig@barcelona.com",
				name: "Jordi Puig",
				phone: "+34666666666",
			},
		},
		createdAt: "2024-07-10",
		description:
			"Habitación con cama doble, escritorio y balcón en un piso con estudiantes internacionales.",
		id: "room_1",
		images: {
			cover:
				"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=958&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
			gallery: [
				"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=958&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
				"https://images.unsplash.com/photo-1615800002234-05c4d488696c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
				"https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
			],
		},
		location: {
			address: "Carrer de Verdi 45",
			city: "Barcelona",
			country: "España",
			lat: 41.4,
			lng: 2.15,
			postalCode: "08012",
		},
		ownerId: "acdada83-28f4-47f6-b0e8-418792bf1706",
		preferences: {
			age: { max: 35, min: 20 },
			currentOccupation: {
				employed: true,
				student: true,
				unemployed: false,
			},
			gender: { female: true, male: true, other: true },
		},
		price: {
			additionalCosts: {
				deposit: 500,
				otherFees: 20,
				utilities: 50,
			},
			amount: 480,
			currency: "EUR",
			isIncluded: false,
			isNegotiable: true,
			localePrice: "480 €",
			paymentFrequency: "monthly",
		},
		rentType: "private-room",
		rules: {
			childrenAllowed: false,
			coupleAllowed: false,
			guestsAllowed: true,
			partiesAllowed: false,
			petsAllowed: false,
			smokingAllowed: false,
		},
		status: "available",
		timings: {
			availableFrom: "2025-09-01",
			maximumStay: { unit: "month", value: 12 },
			minimumStay: { unit: "month", value: 3 },
		},
		title: "Habitación luminosa en piso compartido en Gràcia",
		updatedAt: new Date().toISOString(),
		whoIsLiving: {
			currentTenants: { female: 2, male: 1, other: 0 },
			ownerLivesHere: false,
		},
	},
	{
		commodities: {
			room: {
				area: 10,
				bedType: "single",
				hasBalcony: false,
				hasPrivateBathroom: true,
				hasWindow: true,
				hasWorkingDesk: true,
				isFurnished: true,
			},

			whole: {
				appliances: {
					hasAirConditioning: true,
					hasCoffeeMaker: true,
					hasDishwasher: true,
					hasDryer: true,
					hasElevator: true,
					hasHeating: true,
					hasLaundry: true,
					hasMicrowave: true,
					hasOven: true,
					hasRefrigerator: true,
					hasTV: true,
					hasWifi: true,
					isWheelchairAccessible: true,
				},
				area: 100,
				areUtilitiesIncluded: true,
				bathrooms: 2,
				bedrooms: { individual: 3, shared: 0 },
				extras: {
					hasGarden: false,
					hasParking: true,
					hasPool: false,
					hasTerrace: false,
				},
			},
		},
		contact: {
			owner: {
				email: "lucia@eixampleliving.es",
				name: "Lucía Gómez",
				phone: "+34678901234",
			},
		},
		createdAt: "2024-07-12",
		description:
			"Cómoda habitación con cama individual, escritorio y baño privado en piso moderno y tranquilo.",
		id: "room_2",
		images: {
			cover:
				"https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
			gallery: [
				"https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
			],
		},
		location: {
			address: "Carrer de Mallorca 120",
			city: "Barcelona",
			country: "España",
			lat: 41.3902,
			lng: 2.1649,
			postalCode: "08036",
		},
		ownerId: "acdada83-28f4-47f6-b0e8-418792bf1706",
		preferences: {
			age: { max: 30, min: 22 },
			currentOccupation: {
				employed: true,
				student: true,
				unemployed: false,
			},
			gender: { female: true, male: true, other: false },
		},
		price: {
			additionalCosts: {
				deposit: 600,
				otherFees: 0,
				utilities: 0,
			},
			amount: 600,
			currency: "EUR",
			isIncluded: true,
			isNegotiable: false,
			localePrice: "600 €",
			paymentFrequency: "monthly",
		},
		rentType: "private-room",
		rules: {
			childrenAllowed: false,
			coupleAllowed: false,
			guestsAllowed: false,
			partiesAllowed: false,
			petsAllowed: false,
			smokingAllowed: false,
		},
		status: "available",
		timings: {
			availableFrom: new Date("2025-10-01").toISOString(),
			maximumStay: { unit: "month", value: 12 },
			minimumStay: { unit: "month", value: 6 },
		},
		title: "Habitación individual con baño privado en Eixample",
		updatedAt: new Date().toISOString(),
		whoIsLiving: {
			currentTenants: { female: 0, male: 2, other: 0 },
			ownerLivesHere: false,
		},
	},
	{
		commodities: {
			room: {
				area: 18,
				bedType: "double",
				hasBalcony: false,
				hasPrivateBathroom: false,
				hasWindow: true,
				hasWorkingDesk: true,
				isFurnished: true,
			},

			whole: {
				appliances: {
					hasAirConditioning: true,
					hasCoffeeMaker: false,
					hasDishwasher: false,
					hasDryer: false,
					hasElevator: true,
					hasHeating: false,
					hasLaundry: true,
					hasMicrowave: true,
					hasOven: true,
					hasRefrigerator: true,
					hasTV: true,
					hasWifi: true,
					isWheelchairAccessible: false,
				},
				area: 70,
				areUtilitiesIncluded: false,
				bathrooms: 1,
				bedrooms: { individual: 3, shared: 0 },
				extras: {
					hasGarden: false,
					hasParking: false,
					hasPool: false,
					hasTerrace: true,
				},
			},
		},
		contact: {
			owner: {
				email: "marc@pisosants.com",
				name: "Marc Riera",
				phone: "+34932123456",
			},
		},
		createdAt: "2024-07-15",
		description:
			"Espaciosa habitación doble con salida a terraza privada, ideal para parejas o trabajadores.",
		id: "room_3",
		images: {
			cover:
				"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHJvb218ZW58MHx8MHx8fDA%3D",
			gallery: [
				"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHJvb218ZW58MHx8MHx8fDA%3D",
				"https://images.unsplash.com/photo-1615800002234-05c4d488696c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
				"https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
			],
		},
		location: {
			address: "Carrer de Sants 202",
			city: "Barcelona",
			country: "España",
			lat: 41.3758,
			lng: 2.1343,
			postalCode: "08028",
		},
		ownerId: "acdada83-28f4-47f6-b0e8-418792bf1706",
		preferences: {
			age: { max: 40, min: 25 },
			currentOccupation: {
				employed: true,
				student: false,
				unemployed: false,
			},
			gender: { female: true, male: true, other: true },
		},
		price: {
			additionalCosts: {
				deposit: 700,
				otherFees: 0,
				utilities: 60,
			},
			amount: 700,
			currency: "EUR",
			isIncluded: false,
			isNegotiable: false,
			localePrice: "700 €",
			paymentFrequency: "monthly",
		},
		rentType: "private-room",
		rules: {
			childrenAllowed: false,
			coupleAllowed: true,
			guestsAllowed: true,
			partiesAllowed: false,
			petsAllowed: true,
			smokingAllowed: true,
		},
		status: "booked",
		timings: {
			availableFrom: new Date("2025-09-15").toISOString(),
			maximumStay: { unit: "month", value: 6 },
			minimumStay: { unit: "month", value: 2 },
		},
		title: "Habitación amplia con terraza en Sants",
		updatedAt: new Date().toISOString(),
		whoIsLiving: {
			currentTenants: { female: 1, male: 0, other: 0 },
			ownerLivesHere: true,
		},
	},
	{
		commodities: {
			room: {
				area: 8,
				bedType: "single",
				hasBalcony: false,
				hasPrivateBathroom: false,
				hasWindow: true,
				hasWorkingDesk: true,
				isFurnished: true,
			},

			whole: {
				appliances: {
					hasAirConditioning: false,
					hasCoffeeMaker: false,
					hasDishwasher: false,
					hasDryer: false,
					hasElevator: false,
					hasHeating: true,
					hasLaundry: true,
					hasMicrowave: true,
					hasOven: true,
					hasRefrigerator: true,
					hasTV: false,
					hasWifi: true,
					isWheelchairAccessible: false,
				},
				area: 70,
				areUtilitiesIncluded: false,
				bathrooms: 1,
				bedrooms: { individual: 2, shared: 0 },
				extras: {
					hasGarden: false,
					hasParking: false,
					hasPool: false,
					hasTerrace: false,
				},
			},
		},
		contact: {
			owner: {
				email: "teresa@hogarfamiliar.com",
				name: "Teresa López",
				phone: "+34666666667",
			},
		},
		createdAt: "2024-06-30",
		description:
			"Ideal para estudiantes con presupuesto ajustado, en zona bien comunicada y tranquila.",
		id: "room_4",
		images: {
			cover:
				"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHJvb218ZW58MHx8MHx8fDA%3D",
			gallery: [
				"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHJvb218ZW58MHx8MHx8fDA%3D",
				"https://images.unsplash.com/photo-1615800002234-05c4d488696c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
				"https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww",
			],
		},
		location: {
			address: "Carrer de Rogent 78",
			city: "Barcelona",
			country: "España",
			lat: 41.411,
			lng: 2.1895,
			postalCode: "08026",
		},
		ownerId: "acdada83-28f4-47f6-b0e8-418792bf1706",
		preferences: {
			age: { max: 28, min: 18 },
			currentOccupation: {
				employed: false,
				student: true,
				unemployed: false,
			},
			gender: { female: true, male: false, other: false },
		},
		price: {
			additionalCosts: {
				deposit: 300,
				otherFees: 0,
				utilities: 40,
			},
			amount: 350,
			currency: "EUR",
			isIncluded: false,
			isNegotiable: true,
			localePrice: "350 €",
			paymentFrequency: "monthly",
		},
		rentType: "private-room",
		rules: {
			childrenAllowed: false,
			coupleAllowed: false,
			guestsAllowed: false,
			partiesAllowed: false,
			petsAllowed: false,
			smokingAllowed: false,
		},
		status: "available",
		timings: {
			availableFrom: new Date("2025-08-20").toISOString(),
			maximumStay: { unit: "month", value: 6 },
			minimumStay: { unit: "month", value: 1 },
		},
		title: "Habitación económica en piso familiar en El Clot",
		updatedAt: new Date().toISOString(),
		whoIsLiving: {
			currentTenants: { female: 1, male: 0, other: 0 },
			ownerLivesHere: true,
		},
	},
];
