INSERT INTO public.rooms (
  owner_id,
  title,
  description,
  rent_type,
  status,
  location,
  price,
  commodities,
  rules,
  timings,
  who_is_living,
  contact,
  preferences,
  images,
  created_at,
  updated_at
) VALUES
(
  'acdada83-28f4-47f6-b0e8-418792bf1706',
  'Habitación luminosa en piso compartido en Gràcia',
  'Habitación con cama doble, escritorio y balcón en un piso con estudiantes internacionales.',
  'shared',
  'available',
  '{"address":"Carrer de Verdi 45","city":"Barcelona","country":"España","lat":41.4,"lng":2.15,"postalCode":"08012"}'::jsonb,
  '{"additionalCosts":{"deposit":500,"otherFees":20,"utilities":50},"amount":480,"currency":"EUR","isIncluded":false,"isNegotiable":true,"localePrice":"480 €","paymentFrequency":"monthly"}'::jsonb,
  '{"room":{"area":12,"bedType":"double","hasBalcony":true,"hasPrivateBathroom":false,"hasWindow":true,"hasWorkingDesk":true,"isFurnished":true},"whole":{"appliances":{"hasAirConditioning":false,"hasCoffeeMaker":true,"hasDishwasher":false,"hasDryer":false,"hasElevator":false,"hasHeating":true,"hasLaundry":true,"hasMicrowave":true,"hasOven":true,"hasRefrigerator":true,"hasTV":true,"hasWifi":true,"isWheelchairAccessible":false},"area":90,"areUtilitiesIncluded":false,"bathrooms":1,"bedrooms":{"individual":2,"shared":1},"extras":{"hasGarden":false,"hasParking":false,"hasPool":false,"hasTerrace":true}}}'::jsonb,
  '{"childrenAllowed":false,"coupleAllowed":false,"guestsAllowed":true,"partiesAllowed":false,"petsAllowed":false,"quietHours":{"from":"22:00","to":"08:00"},"smokingAllowed":false}'::jsonb,
  '{"availableFrom":"2025-09-01","maximumStay":{"unit":"month","value":12},"minimumStay":{"unit":"month","value":3}}'::jsonb,
  '{"currentTenants":{"female":2,"male":1,"other":0},"ownerLivesHere":false}'::jsonb,
  '{"owner":{"email":"jordi.puig@barcelona.com","name":"Jordi Puig","phone":"+34666666666"}}'::jsonb,
  '{"age":{"max":35,"min":20},"currentOccupation":{"employed":true,"other":false,"student":true,"unemployed":false},"gender":{"female":true,"male":true,"other":true}}'::jsonb,
  '{"gallery":["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=958&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D","https://images.unsplash.com/photo-1615800002234-05c4d488696c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww","https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww"],"main":0}'::jsonb,
  '2024-07-10',
  '2025-08-29'
),
(
  'acdada83-28f4-47f6-b0e8-418792bf1706',
  'Habitación individual con baño privado en Eixample',
  'Cómoda habitación con cama individual, escritorio y baño privado en piso moderno y tranquilo.',
  'shared',
  'available',
  '{"address":"Carrer de Mallorca 120","city":"Barcelona","country":"España","lat":41.3902,"lng":2.1649,"postalCode":"08036"}'::jsonb,
  '{"additionalCosts":{"deposit":600,"otherFees":0,"utilities":0},"amount":600,"currency":"EUR","isIncluded":true,"isNegotiable":false,"localePrice":"600 €","paymentFrequency":"monthly"}'::jsonb,
  '{"room":{"area":10,"bedType":"single","hasBalcony":false,"hasPrivateBathroom":true,"hasWindow":true,"hasWorkingDesk":true,"isFurnished":true},"whole":{"appliances":{"hasAirConditioning":true,"hasCoffeeMaker":true,"hasDishwasher":true,"hasDryer":true,"hasElevator":true,"hasHeating":true,"hasLaundry":true,"hasMicrowave":true,"hasOven":true,"hasRefrigerator":true,"hasTV":true,"hasWifi":true,"isWheelchairAccessible":true},"area":100,"areUtilitiesIncluded":true,"bathrooms":2,"bedrooms":{"individual":3,"shared":0},"extras":{"hasGarden":false,"hasParking":true,"hasPool":false,"hasTerrace":false}}}'::jsonb,
  '{"childrenAllowed":false,"coupleAllowed":false,"guestsAllowed":false,"partiesAllowed":false,"petsAllowed":false,"quietHours":{"from":"22:00","to":"08:00"},"smokingAllowed":false}'::jsonb,
  '{"availableFrom":"2025-10-01","maximumStay":{"unit":"month","value":12},"minimumStay":{"unit":"month","value":6}}'::jsonb,
  '{"currentTenants":{"female":0,"male":2,"other":0},"ownerLivesHere":false}'::jsonb,
  '{"owner":{"email":"lucia@eixampleliving.es","name":"Lucía Gómez","phone":"+34678901234"}}'::jsonb,
  '{"age":{"max":30,"min":22},"currentOccupation":{"employed":true,"other":false,"student":true,"unemployed":false},"gender":{"female":true,"male":true,"other":false}}'::jsonb,
  '{"gallery":["https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHNhbGElMjBkZSUyMGVzdGFyfGVufDB8fDB8fHww"],"main":0}'::jsonb,
  '2024-07-12',
  '2025-08-29'
);
