INSERT INTO public.rooms (
  owner_id,
  title,
  description,
  rent_type,
  status,
  location,
  price,
  commodities,
  rules,
  timings,
  who_is_living,
  contact,
  preferences,
  created_at,
  updated_at
) VALUES
(
  'acdada83-28f4-47f6-b0e8-418792bf1706',
  'Habitación luminosa en el centro',
  'Habitación individual con balcón, ideal para estudiante.',
  'room',
  'available',
  '{"address": "Carrer de Balmes 123", "city": "Barcelona", "country": "ES", "lat": 41.387, "lng": 2.168, "postalCode": "08006"}'::jsonb,
  '{"amount": 550, "currency": "EUR", "isIncluded": true, "isNegotiable": false, "localePrice": "€550", "paymentFrequency": "monthly", "additionalCosts": {"deposit": 550, "utilities": 50}}'::jsonb,
  '{"room":{"area":15,"bedType":"single","hasBalcony":true,"hasPrivateBathroom":false,"hasWindow":true,"hasWorkingDesk":true,"isFurnished":true},"whole":{"area":90,"areUtilitiesIncluded":true,"bathrooms":2,"bedrooms":{"individual":2,"shared":1},"appliances":{"hasAirConditioning":true,"hasCoffeeMaker":true,"hasDishwasher":true,"hasDryer":false,"hasElevator":true,"hasHeating":true,"hasLaundry":false,"hasMicrowave":true,"hasOven":true,"hasRefrigerator":true,"hasTV":true,"hasWifi":true,"isWheelchairAccessible":true},"extras":{"hasGarden":false,"hasParking":true,"hasPool":false,"hasTerrace":true}}}'::jsonb,
  '{"childrenAllowed":true,"coupleAllowed":true,"guestsAllowed":true,"partiesAllowed":false,"petsAllowed":false,"quietHours":{"from":"22:00","to":"08:00"},"smokingAllowed":false}'::jsonb,
  '{"availableFrom":"2025-09-01T00:00:00Z","availableUntil":"2026-06-30T00:00:00Z","minimumStay":{"unit":"month","value":6}}'::jsonb,
  '{"currentTenants":{"female":1,"male":0,"other":0},"ownerLivesHere":false}'::jsonb,
  '{"owner":{"email":"owner1@example.com","name":"Owner One","phone":"+34123456789"}}'::jsonb,
  '{"age":{"min":18,"max":30},"currentOccupation":{"student":true,"employed":false,"unemployed":false,"other":false},"gender":{"female":true,"male":true,"other":true}}'::jsonb,
  now(),
  now()
),
(
  'acdada83-28f4-47f6-b0e8-418792bf1706',
  'Apartamento compartido moderno',
  'Habitación en apartamento compartido con dos roommates.',
  'shared',
  'available',
  '{"address": "Carrer de Mallorca 200", "city": "Barcelona", "country": "ES", "lat": 41.397, "lng": 2.160, "postalCode": "08036"}'::jsonb,
  '{"amount": 400, "currency": "EUR", "isIncluded": true, "isNegotiable": true, "localePrice": "€400", "paymentFrequency": "monthly", "additionalCosts": {"deposit": 400, "utilities": 50}}'::jsonb,
  '{"room":{"area":12,"bedType":"single","hasBalcony":false,"hasPrivateBathroom":false,"hasWindow":true,"hasWorkingDesk":true,"isFurnished":true},"whole":{"area":70,"areUtilitiesIncluded":true,"bathrooms":1,"bedrooms":{"individual":1,"shared":2},"appliances":{"hasAirConditioning":false,"hasCoffeeMaker":true,"hasDishwasher":false,"hasDryer":false,"hasElevator":true,"hasHeating":true,"hasLaundry":false,"hasMicrowave":true,"hasOven":true,"hasRefrigerator":true,"hasTV":true,"hasWifi":true,"isWheelchairAccessible":false},"extras":{"hasGarden":false,"hasParking":false,"hasPool":false,"hasTerrace":false}}}'::jsonb,
  '{"childrenAllowed":false,"coupleAllowed":true,"guestsAllowed":true,"partiesAllowed":false,"petsAllowed":true,"quietHours":false,"smokingAllowed":false}'::jsonb,
  '{"availableFrom":"2025-09-15T00:00:00Z","minimumStay":{"unit":"month","value":3}}'::jsonb,
  '{"currentTenants":{"female":1,"male":1,"other":0},"ownerLivesHere":true}'::jsonb,
  '{"owner":{"email":"owner2@example.com","name":"Owner Two","phone":"+34111222333"}}'::jsonb,
  '{"age":{"min":20,"max":35},"currentOccupation":{"student":true,"employed":true,"unemployed":false,"other":false},"gender":{"female":true,"male":true,"other":false}}'::jsonb,
  now(),
  now()
),
(
  'acdada83-28f4-47f6-b0e8-418792bf1706',
  'Piso entero amueblado',
  'Alquila el piso completo con todos los servicios incluidos.',
  'entire',
  'available',
  '{"address": "Carrer de Provença 50", "city": "Barcelona", "country": "ES", "lat": 41.397, "lng": 2.161, "postalCode": "08012"}'::jsonb,
  '{"amount": 1200, "currency": "EUR", "isIncluded": true, "isNegotiable": false, "localePrice": "€1200", "paymentFrequency": "monthly", "additionalCosts": {"deposit": 1200, "utilities": 150}}'::jsonb,
  '{"whole":{"area":120,"areUtilitiesIncluded":true,"bathrooms":2,"bedrooms":{"individual":0,"shared":0},"appliances":{"hasAirConditioning":true,"hasCoffeeMaker":true,"hasDishwasher":true,"hasDryer":true,"hasElevator":true,"hasHeating":true,"hasLaundry":true,"hasMicrowave":true,"hasOven":true,"hasRefrigerator":true,"hasTV":true,"hasWifi":true,"isWheelchairAccessible":true},"extras":{"hasGarden":true,"hasParking":true,"hasPool":true,"hasTerrace":true}}}'::jsonb,
  '{"childrenAllowed":true,"coupleAllowed":true,"guestsAllowed":true,"partiesAllowed":true,"petsAllowed":true,"quietHours":false,"smokingAllowed":true}'::jsonb,
  '{"availableFrom":"2025-10-01T00:00:00Z","minimumStay":{"unit":"month","value":1},"maximumStay":{"unit":"month","value":12}}'::jsonb,
  '{"currentTenants":{"female":0,"male":0,"other":0},"ownerLivesHere":false}'::jsonb,
  '{"owner":{"email":"owner3@example.com","name":"Owner Three","phone":"+34987654321"}}'::jsonb,
  '{"age":{"min":18,"max":40},"currentOccupation":{"student":false,"employed":true,"unemployed":false,"other":true},"gender":{"female":true,"male":true,"other":true}}'::jsonb,
  now(),
  now()
);
