import type { User } from "src/entities/user/user";

export const mockUsers: User[] = [
	{
		aboutMe: "Estudiante de medicina en la UB, tranquila, ordenada y no fumo.",
		authProvider: "google",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "2000-04-12",
		createdAt: new Date("2024-11-20"),
		email: "lucia.garcia@gmail.com",
		gender: "female",
		id: "user_9",

		languagesSpoken: ["es", "ca", "en"],
		lastname: "García",
		name: "Lucía",
		occupation: "student",
		phone: "+34678901234",
		preferences: {
			age: {
				max: 30,
				min: 20,
			},
			duration: {
				unit: "month",
				value: 10,
			},
			gender: {
				female: true,
				male: true,
				other: false,
			},
			maxBudget: 600,
			moveInDate: "2025-09-01",
			occupation: {
				employed: true,
				other: false,
				student: true,
				unemployed: false,
			},
			rentType: ["shared"],
		},
		providerId: "google-oauth2|999999999999999",
		updatedAt: new Date(),
	},
	{
		aboutMe:
			"Ingeniero de software, tranquilo y aficionado al ciclismo. No fumador.",
		authProvider: "credentials",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1996-02-20",
		createdAt: new Date("2024-10-05"),
		email: "carlos.martin@example.com",
		gender: "male",
		id: "user_1",
		languagesSpoken: ["es", "en"],
		lastname: "Martín",
		name: "Carlos",
		occupation: "employed",
		phone: "+34611112222",
		preferences: {
			age: { max: 38, min: 22 },
			duration: { unit: "month", value: 12 },
			gender: { female: true, male: true, other: true },
			maxBudget: 800,
			moveInDate: "2025-09-15",
			occupation: {
				employed: true,
				other: true,
				student: false,
				unemployed: false,
			},
			rentType: ["shared", "room"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe:
			"Diseñadora gráfica, me encanta cocinar y mantener el piso acogedor.",
		authProvider: "google",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1998-09-10",
		createdAt: new Date("2024-09-21"),
		email: "ana.lopez@example.com",
		gender: "female",
		id: "user_2",
		languagesSpoken: ["es", "ca"],
		lastname: "López",
		name: "Ana",
		occupation: "employed",
		phone: "+34622223333",
		preferences: {
			age: { max: 35, min: 20 },
			duration: { unit: "month", value: 6 },
			gender: { female: true, male: false, other: true },
			maxBudget: 650,
			moveInDate: "2025-10-01",
			occupation: {
				employed: true,
				other: true,
				student: true,
				unemployed: false,
			},
			rentType: ["shared"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe: "Doctorando en física. Busco ambiente tranquilo para estudiar.",
		authProvider: "facebook",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1995-01-05",
		createdAt: new Date("2024-08-15"),
		email: "javier.santos@example.com",
		gender: "male",
		id: "user_3",
		languagesSpoken: ["es", "en", "fr"],
		lastname: "Santos",
		name: "Javier",
		occupation: "student",
		phone: "+34633334444",
		preferences: {
			age: { max: 32, min: 21 },
			duration: { unit: "month", value: 9 },
			gender: { female: true, male: true, other: true },
			maxBudget: 550,
			moveInDate: "2025-09-01",
			occupation: {
				employed: true,
				other: true,
				student: true,
				unemployed: false,
			},
			rentType: ["shared", "room"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe: "Barista y músico. Tranquilo, limpio y respetuoso. Mascotas OK.",
		authProvider: "credentials",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1993-07-18",
		createdAt: new Date("2024-07-30"),
		email: "sergio.ruiz@example.com",
		gender: "male",
		id: "user_4",
		languagesSpoken: ["es", "en"],
		lastname: "Ruiz",
		name: "Sergio",
		occupation: "other",
		phone: "+34644445555",
		preferences: {
			age: { max: 40, min: 20 },
			duration: { unit: "month", value: 6 },
			gender: { female: true, male: true, other: true },
			maxBudget: 500,
			moveInDate: "2025-08-25",
			occupation: {
				employed: true,
				other: true,
				student: true,
				unemployed: false,
			},
			rentType: ["shared"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe: "Busco mi primer piso en Barcelona. No me importa compartir.",
		authProvider: "google",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "2002-12-03",
		createdAt: new Date("2025-01-10"),
		email: "mireia.camps@example.com",
		gender: "female",
		id: "user_5",
		languagesSpoken: ["ca", "es", "en"],
		lastname: "Camps",
		name: "Mireia",
		occupation: "student",
		phone: "+34655556666",
		preferences: {
			age: { max: 30, min: 18 },
			duration: { unit: "month", value: 10 },
			gender: { female: true, male: true, other: true },
			maxBudget: 450,
			moveInDate: "2025-09-10",
			occupation: {
				employed: false,
				other: true,
				student: true,
				unemployed: false,
			},
			rentType: ["shared"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe: "Recién llegado por trabajo. Busco habitación cerca del centro.",
		authProvider: "facebook",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1990-05-28",
		createdAt: new Date("2024-12-08"),
		email: "andres.gomez@example.com",
		gender: "male",
		id: "user_6",
		languagesSpoken: ["es", "en", "pt"],
		lastname: "Gómez",
		name: "Andrés",
		occupation: "employed",
		phone: "+34666667777",
		preferences: {
			age: { max: 45, min: 23 },
			duration: { unit: "year", value: 1 },
			gender: { female: true, male: true, other: true },
			maxBudget: 1000,
			moveInDate: "2025-09-05",
			occupation: {
				employed: true,
				other: true,
				student: false,
				unemployed: false,
			},
			rentType: ["room", "entire"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe: "Prefiero ambiente social, me gusta organizar cenas y juegos.",
		authProvider: "credentials",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1999-11-14",
		createdAt: new Date("2024-11-02"),
		email: "laura.perez@example.com",
		gender: "female",
		id: "user_7",
		languagesSpoken: ["es", "en", "it"],
		lastname: "Perez",
		name: "Laura",
		occupation: "employed",
		phone: "+34677778888",
		preferences: {
			age: { max: 36, min: 21 },
			duration: { unit: "month", value: 12 },
			gender: { female: true, male: true, other: true },
			maxBudget: 700,
			moveInDate: "2025-09-20",
			occupation: {
				employed: true,
				other: true,
				student: true,
				unemployed: false,
			},
			rentType: ["shared"],
		},
		updatedAt: new Date(),
	},
	{
		aboutMe:
			"Prefiero privacidad. Busco estudio o habitación grande con baño privado.",
		authProvider: "google",
		avatarUrl: "https://thispersondoesnotexist.com/",
		birthDate: "1987-03-22",
		createdAt: new Date("2024-06-18"),
		email: "nuria.soler@example.com",
		gender: "prefer_not_to_say",
		id: "user_8",
		languagesSpoken: ["es", "ca", "en", "de"],
		lastname: "Sol",
		name: "Núria",
		occupation: "other",
		phone: "+34688889999",
		preferences: {
			age: { max: 50, min: 25 },
			duration: { unit: "year", value: 1 },
			gender: { female: true, male: true, other: true },
			maxBudget: 1200,
			moveInDate: "2025-10-10",
			occupation: {
				employed: true,
				other: true,
				student: false,
				unemployed: false,
			},
			rentType: ["room", "entire"],
		},
		updatedAt: new Date(),
	},
];
